/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Brenwltrs (https://sketchfab.com/Brenwltrs)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pile-of-books-822e51eef741496d926bea1fbc32db7b
Title: Pile of books
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Book(props) {
  const { nodes, materials } = useGLTF("/assets/3d/pile_of_books.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box002_ORANGE_0.geometry}
        material={materials.ORANGE}
        position={[-30.973, 4.635, -56.542]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1.058, 0.677, 0.205]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box003_RED_0.geometry}
        material={materials.material}
        position={[-30.621, 15.54, -57.207]}
        rotation={[-Math.PI / 2, 0, -0.061]}
        scale={[1.058, 0.677, 0.205]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box004_blue_0.geometry}
        material={materials.blue}
        position={[-30.838, 36.701, -57.289]}
        rotation={[-Math.PI / 2, 0, -0.067]}
        scale={[1.058, 0.677, 0.205]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box005_black_0.geometry}
        material={materials.black}
        position={[-30.649, 26.373, -57.794]}
        rotation={[-Math.PI / 2, 0, -0.067]}
        scale={[1.058, 0.677, 0.205]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box006_green_0.geometry}
        material={materials.green}
        position={[-28.814, 41.929, -58.585]}
        rotation={[-Math.PI / 2, 0, -0.067]}
        scale={[1.058, 0.677, 0.205]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box007_purple_0.geometry}
        material={materials.purple}
        position={[-28.771, 31.601, -58.089]}
        rotation={[-Math.PI / 2, 0, -0.105]}
        scale={[1.058, 0.677, 0.205]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box008_pink_0.geometry}
        material={materials.pink}
        position={[-29.546, 20.768, -57.15]}
        rotation={[-Math.PI / 2, 0, -0.036]}
        scale={[1.058, 0.677, 0.205]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box009_Cyan_0.geometry}
        material={materials.Cyan}
        position={[-29.131, 9.862, -57.596]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1.058, 0.677, 0.205]}
      />
    </group>
  );
}