/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: djetty (https://sketchfab.com/djetty)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-pen-7a09c75d40e84b10acfd4f8c40e08375
Title: Old Pen
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Pen(props) {
  const { nodes, materials } = useGLTF("/assets/3d/old_pen.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.None}
        position={[-0.26, 0, -0.142]}
        rotation={[-Math.PI / 2, 0, -0.999]}
      />
    </group>
  );
}
