import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from '@/components/Providers/NextProvider'
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className='bg-white'>
          <ClerkProvider>
            <Providers>
              {children}
            </Providers>
          </ClerkProvider>
        </main>
      </body>
    </html>
  )
}
