import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from '@/components/Providers/NextProviders'
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: '',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider>
          <main className="dark w-full h-screen text-foreground bg-background">
            <Providers>
              {children}
            </Providers>
          </main>
        </ClerkProvider>
      </body>
    </html>
  )
}
